### ISSUE TITLE
Install on Visual Studio 2019 fails

### ISSUE THREAD

**Issue by ivanjx** [EgorBo/Xamaridea#20]
The title says it all. When i tried to install this to my vs2019 installation, it just fail.

![image](https://user-images.githubusercontent.com/12814796/57187913-4a6ffa80-6f20-11e9-90d2-33a84fcd9c3a.png)

Log:
```
05/05/2019 10:25:12 - Microsoft VSIX Installer
05/05/2019 10:25:12 - -------------------------------------------
05/05/2019 10:25:12 - vsixinstaller.exe version:
05/05/2019 10:25:12 - 16.0.2264
05/05/2019 10:25:12 - -------------------------------------------
05/05/2019 10:25:12 - Command line parameters:
05/05/2019 10:25:12 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\Downloads\Xamaridea.VisualStudioPlugin.vsix
05/05/2019 10:25:12 - -------------------------------------------
05/05/2019 10:25:12 - Microsoft VSIX Installer
05/05/2019 10:25:12 - -------------------------------------------
05/05/2019 10:25:12 - Initializing Install...
05/05/2019 10:25:12 - Extension Details...
05/05/2019 10:25:12 - 	Identifier         : c3535449-011a-480d-b116-f2be70bf4d15
05/05/2019 10:25:12 - 	Name               : XamarIDEA
05/05/2019 10:25:12 - 	Author             : EgorBo
05/05/2019 10:25:12 - 	Version            : 1.0.2
05/05/2019 10:25:12 - 	Description        : Visual Studio extension, with it you can open your .axml files (Xamarin.Android) in IntelliJ IDEA or Android Studio. It creates a fake android project and uses resources from your Xamarin.Android project by link so every change made in Android IDE will be saved.
05/05/2019 10:25:12 - 	Locale             : en-US
05/05/2019 10:25:12 - 	MoreInfoURL        : https://github.com/EgorBo/Xamaridea
05/05/2019 10:25:12 - 	InstalledByMSI     : False
05/05/2019 10:25:12 - 	SupportedFrameworkVersionRange : [4.5,)
05/05/2019 10:25:12 - 
05/05/2019 10:25:12 - 	SignatureState     : Unsigned
05/05/2019 10:25:12 - 	Supported Products : 
05/05/2019 10:25:12 - 		Microsoft.VisualStudio.IntegratedShell
05/05/2019 10:25:12 - 			Version : [12.0,16.0)
05/05/2019 10:25:12 - 		Microsoft.VisualStudio.Community
05/05/2019 10:25:12 - 			Version : [12.0,16.0)
05/05/2019 10:25:12 - 		Microsoft.VisualStudio.Pro
05/05/2019 10:25:12 - 			Version : [11.0,16.0)
05/05/2019 10:25:12 - 		Microsoft.VisualStudio.Enterprise
05/05/2019 10:25:12 - 			Version : [11.0,16.0)
05/05/2019 10:25:12 - 		Microsoft.VisualStudio.Premium
05/05/2019 10:25:12 - 			Version : [11.0,16.0)
05/05/2019 10:25:12 - 		Microsoft.VisualStudio.Ultimate
05/05/2019 10:25:12 - 			Version : [11.0,16.0)
05/05/2019 10:25:12 - 		Microsoft.VisualStudio.VSLS
05/05/2019 10:25:12 - 			Version : [12.0,16.0)
05/05/2019 10:25:12 - 
05/05/2019 10:25:12 - 	References         : 
05/05/2019 10:25:12 - 		-------------------------------------------------------
05/05/2019 10:25:12 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
05/05/2019 10:25:12 - 		Name         : Visual Studio MPF 14.0
05/05/2019 10:25:12 - 		Version      : [14.0]
05/05/2019 10:25:12 - 		MoreInfoURL  : 
05/05/2019 10:25:12 - 		Nested       : No
05/05/2019 10:25:12 - 
05/05/2019 10:25:12 - 	Prerequisites      : 
05/05/2019 10:25:12 - 		-------------------------------------------------------
05/05/2019 10:25:12 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
05/05/2019 10:25:12 - 		Name         : Visual Studio core editor
05/05/2019 10:25:12 - 		Version      : [14.0,16.0)
05/05/2019 10:25:12 - 
05/05/2019 10:25:12 - Signature Details...
05/05/2019 10:25:12 - 	Extension is not signed.
05/05/2019 10:25:12 - 
05/05/2019 10:25:12 - Searching for applicable products...
05/05/2019 10:25:12 - Found installed product - Global Location
05/05/2019 10:25:12 - Found installed product - Visual Studio Community 2019
05/05/2019 10:25:12 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by nitewulf** [comment]
I'd love to get this extension working as well. I get an error that says a reference to visual studio mpf 14.0 missing.

**Comment by MatthewSannes** [comment]
Really would like this to work again on VS 2019 too!

**Comment by michaelm7456** [comment]
@EgorBo, I've raised a Pull Request [here](https://github.com/EgorBo/Xamaridea/pull/21) with some changes to allow the Extension to work with Visual Studio 2019.

Is it possible to have this Pull Request reviewed and the latest version of this Extension published to the Visual Studio Gallery if the changes meet your approval and it's not too much trouble?

Many thanks for the excellent Extension!

**Comment by Zintom** [comment]
As Egor hasn't responded to a Pull Request in *three years*;

I took it upon myself to build my own extension, available [here](https://marketplace.visualstudio.com/items?itemName=Zintom.XamarinStudioLinker)
